version: '3.8'

# Development Docker Compose Configuration
# Use: docker-compose -f docker-compose.dev.yml up

services:
  # ============================================
  # Development Application Service
  # ============================================
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nogl-landing-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      # =============================================================================
      # Core Configuration
      # =============================================================================
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      
      # =============================================================================
      # Database
      # =============================================================================
      - DATABASE_URL=${DATABASE_URL}
      
      # =============================================================================
      # NextAuth Configuration
      # =============================================================================
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      
      # =============================================================================
      # App Configuration
      # =============================================================================
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - SITE_URL=${SITE_URL:-http://localhost:3000}
      - SITE_NAME=${SITE_NAME:-NOGL}
      - NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN:-localhost:3000}
      - NEXT_PUBLIC_APP_SUBDOMAIN=${NEXT_PUBLIC_APP_SUBDOMAIN:-app}
      - NEXT_PUBLIC_AUTH_SUBDOMAIN=${NEXT_PUBLIC_AUTH_SUBDOMAIN:-}
      
      # =============================================================================
      # Email Configuration
      # =============================================================================
      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      
      # =============================================================================
      # Ghost CMS Configuration
      # =============================================================================
      - NEXT_PUBLIC_GHOST_URL=${NEXT_PUBLIC_GHOST_URL}
      - NEXT_PUBLIC_GHOST_CONTENT_API_KEY=${NEXT_PUBLIC_GHOST_CONTENT_API_KEY}
      - GHOST_API_URL=${GHOST_API_URL}
      - GHOST_CONTENT_API_KEY=${GHOST_CONTENT_API_KEY}
      
      # =============================================================================
      # Google OAuth
      # =============================================================================
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      
      # =============================================================================
      # Payment Processing (Stripe)
      # =============================================================================
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      
      # =============================================================================
      # Builder.io
      # =============================================================================
      - NEXT_PUBLIC_BUILDER_API_KEY=${NEXT_PUBLIC_BUILDER_API_KEY}
      
      # =============================================================================
      # Analytics
      # =============================================================================
      - NEXT_PUBLIC_GOOGLE_TAG_ID=${NEXT_PUBLIC_GOOGLE_TAG_ID}
      
      # =============================================================================
      # Optional Services (uncomment when needed)
      # =============================================================================
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - UPLOADTHING_SECRET=${UPLOADTHING_SECRET}
      # - UPLOADTHING_APP_ID=${UPLOADTHING_APP_ID}
    depends_on:
      db-dev:
        condition: service_healthy
    networks:
      - dev-network
    command: npm run dev

  # ============================================
  # Development Database Service
  # ============================================
  db-dev:
    image: postgres:16-alpine
    container_name: nogl-landing-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nogl_dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
