// Mock dataset for the forecasting / alert overview screen.
// In production this is sourced from the inventory + sales pipelines;
// the shape is intentionally identical to the production /api/forecasting/products payload.
import type { ForecastRow, ForecastTab } from "@/components/forecasting/types";

export const MOCK_FORECAST_ROWS: ForecastRow[] = [
    { id: 1, badges: ["new"], name: "Classic Polo 6-Pack", size: "S", sku: "TCT4002GREENEUTRALPOLG0PKS", warehouses: 1, wh: "Example Warehouse...",
        reorder: { label: "Transfer 37 units", type: "blue", days: "3 days", daysColor: "red" },
        stock: { current: 152, incoming: 0, preorder: 0, reserved: 5 },
        oos: { date: "28.04.2026", eta: "in 2 months", tone: "orange" },
        reach: { days: "63 days", label: "Reorder", segs: [1, 1, 0, 0, 0] },
        oosImpact: { ok: false, potential: true, value: null, text: "Potential loss" },
        relCurrent: null, relIncoming: null, oosImpactSort: 0 },

    { id: 2, badges: ["new"], name: "Classic Polo 6-Pack", size: "M", sku: "TCT4002GREENEUTRALPOLG0PKM", warehouses: 1, wh: "Example Warehouse...",
        reorder: { label: "Reorder 0 units", type: "purple", days: "1489 days", daysColor: "purple" },
        stock: { current: 444, incoming: 0, preorder: 0, reserved: 0 },
        oos: { date: "24.07.2030", eta: "in 4 years", tone: "muted" },
        reach: { days: "1611 days", label: "Overstock", segs: [1, 1, 1, 1, 1] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: { value: "6.752 €", units: "386 units releasable" }, relIncoming: null, oosImpactSort: 0 },

    { id: 3, badges: [], name: "Classic Polo 6-Pack", size: "XL", sku: "TCT4002GREENEUTRALPOLG0GPKXL", warehouses: 1, wh: "Example Warehouse...",
        reorder: { label: "Reorder 0 units", type: "purple", days: "2664 days", daysColor: "purple" },
        stock: { current: 1332, incoming: 0, preorder: 0, reserved: 0 },
        oos: { date: "01.06.2033", eta: "in 7 years", tone: "muted" },
        reach: { days: "2664 days", label: "Overstock", segs: [1, 1, 1, 1, 1] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: { value: "20.772 €", units: "1187 units releasable" }, relIncoming: null, oosImpactSort: 0 },

    { id: 4, badges: [], name: "Classic Polo 6-Pack", size: "XL", sku: "TCT4002GREENEUTRALPOLG0GPKXL2", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 0 units", type: "purple", days: "8 days", daysColor: "orange" },
        stock: { current: 3024, incoming: 5000, preorder: 0, reserved: 1 },
        oos: { date: "01.05.2026", eta: "in 2 months", tone: "orange" },
        reach: { days: "66 days", label: "Reorder", segs: [1, 1, 0, 0, 0] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: null, relIncoming: { value: "19.387 €", units: "1108 units releasable" }, oosImpactSort: 0 },

    { id: 5, badges: [], name: "Classic Polo 6-Pack", size: "2XL", sku: "TCT4002GREENEUTRALPOLG0GPKZXL", warehouses: 1, wh: "Example Warehouse...",
        reorder: { label: "Transfer 0 units", type: "blue", days: "84 days", daysColor: "blue" },
        stock: { current: 1417, incoming: 0, preorder: 0, reserved: 8 },
        oos: { date: "29.07.2026", eta: "in 5 months", tone: "muted" },
        reach: { days: "155 days", label: "Overstock", segs: [1, 1, 1, 1, 0] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: { value: "4.286 €", units: "245 units releasable" }, relIncoming: null, oosImpactSort: 0 },

    { id: 6, badges: [], name: "Classic Polo 6-Pack", size: "3XL", sku: "TCT4002GREENEUTRALPOLG0GPKZXL3", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 7021 units", type: "purple", days: "9 days", daysColor: "red" },
        stock: { current: 12017, incoming: 0, preorder: 0, reserved: 0 },
        oos: { date: "23.02.2026", eta: "a day ago", tone: "red" },
        reach: { days: "0 days", label: "Out of stock", segs: [0, 0, 0, 0, 0] },
        oosImpact: { ok: false, potential: false, value: "22,9k €", units: "184 units" },
        relCurrent: null, relIncoming: null, oosImpactSort: 22900 },

    { id: 7, badges: [], name: "Classic Crews 10-Pack", size: "S", sku: "TCT4000CREW22450PKS", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Optional 0 units", type: "gray", days: "16 days", daysColor: "blue" },
        stock: { current: 5021, incoming: 5000, preorder: 0, reserved: 0 },
        oos: { date: "19.07.2026", eta: "in 5 months", tone: "muted" },
        reach: { days: "145 days", label: "Overstock", segs: [1, 1, 1, 1, 0] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: { value: "305 €", units: "16 units releasable" }, relIncoming: null, oosImpactSort: 0 },

    { id: 8, badges: [], name: "Classic Crews 10-Pack", size: "M", sku: "TCT4000CREW22450PKM", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 0 units", type: "purple", days: "2 days", daysColor: "red" },
        stock: { current: 3641, incoming: 0, preorder: 0, reserved: 0 },
        oos: { date: "27.04.2026", eta: "in 2 months", tone: "orange" },
        reach: { days: "62 days", label: "Reorder", segs: [1, 1, 0, 0, 0] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: null, relIncoming: null, oosImpactSort: 0 },

    { id: 9, badges: [], name: "Classic Crews 10-Pack", size: "PKL", sku: "TCT4000CREW22450PKL", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 0 units", type: "purple", days: "3 days", daysColor: "red" },
        stock: { current: 1187, incoming: 0, preorder: 0, reserved: 0 },
        oos: { date: "28.04.2026", eta: "in 2 months", tone: "orange" },
        reach: { days: "63 days", label: "Reorder", segs: [1, 1, 0, 0, 0] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: null, relIncoming: { value: "36.588 €", units: "1952 units releasable" }, oosImpactSort: 0 },

    { id: 10, badges: [], name: "Classic Crews 10-Pack", size: "XL", sku: "TCT4000CREW22450PXKL", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 0 units", type: "purple", days: "111 days", daysColor: "purple" },
        stock: { current: 2087, incoming: 0, preorder: 1, reserved: 0 },
        oos: { date: "11.09.2026", eta: "in 7 months", tone: "muted" },
        reach: { days: "199 days", label: "Overstock", segs: [1, 1, 1, 1, 1] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: { value: "7.985 €", units: "426 units releasable" }, relIncoming: null, oosImpactSort: 0 },

    { id: 11, badges: [], name: "Black & Charcoal Active V-Neck", size: "S", sku: "TCT41030LKCH0Y2PKS", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 1017 units", type: "purple", days: "7 days", daysColor: "orange" },
        stock: { current: 2092, incoming: 0, preorder: 0, reserved: 0 },
        oos: { date: "26.05.2026", eta: "in 2 months", tone: "orange" },
        reach: { days: "81 days", label: "Reorder", segs: [1, 1, 0, 0, 0] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: { value: "1.686 €", units: "193 units releasable" }, relIncoming: null, oosImpactSort: 0 },

    { id: 12, badges: [], name: "Classic Crew 3-Pack", size: "L", sku: "TCT6000WKLY0L22363PKL", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 2101 units", type: "purple", days: "1-3 days", daysColor: "red" },
        stock: { current: 3255, incoming: 4, preorder: 0, reserved: 2 },
        oos: { date: "18.05.2026", eta: "in 3 months", tone: "orange" },
        reach: { days: "83 days", label: "Critical", segs: [1, 1, 0, 0, 0] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: { value: "1.369 €", units: "157 units releasable" }, relIncoming: { value: "35 €", units: "4 units releasable" }, oosImpactSort: 0 },

    { id: 13, badges: [], name: "Classic Crew 3-Pack", size: "2XL", sku: "TCT6000WKLY0L2263PK2XL", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Optional 0 units", type: "gray", days: "38 days", daysColor: "orange" },
        stock: { current: 1285, incoming: 0, preorder: 0, reserved: 1 },
        oos: { date: "31.05.2026", eta: "in 3 months", tone: "muted" },
        reach: { days: "96 days", label: "OK", segs: [1, 1, 1, 1, 0] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: { value: "1.337 €", units: "153 units releasable" }, relIncoming: null, oosImpactSort: 0 },

    { id: 14, badges: ["new"], name: "Classic Polo 3-Pack", size: "", sku: "TCT4002WKLY0L2263PKS", warehouses: 1, wh: "Example Warehouse...",
        reorder: { label: "Reorder 0 units", type: "purple", days: "133 days", daysColor: "purple" },
        stock: { current: 2064, incoming: 3000, preorder: 0, reserved: 2 },
        oos: { date: "05.09.2026", eta: "in 5 months", tone: "muted" },
        reach: { days: "193 days", label: "Overstock", segs: [1, 1, 1, 1, 0] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: { value: "672 €", units: "60 units releasable" }, relIncoming: { value: "18.845 €", units: "1675 units releasable" }, oosImpactSort: 0 },

    { id: 15, badges: [], name: "Classic Crew 3-Pack", size: "M", sku: "TCT6000WKLY0L2263PKM", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 0 units", type: "purple", days: "15 days", daysColor: "orange" },
        stock: { current: 943, incoming: 3000, preorder: 0, reserved: 0 },
        oos: { date: "09.09.2026", eta: "in 7 months", tone: "muted" },
        reach: { days: "197 days", label: "Overstock", segs: [1, 1, 1, 1, 0] },
        oosImpact: { ok: true, text: "No Future OOS impact" },
        relCurrent: { value: "422 €", units: "48 units releasable" }, relIncoming: { value: "5.030 €", units: "575 units releasable" }, oosImpactSort: 0 },

    { id: 16, badges: [], name: "Variety Tees 7-Pack", size: "", sku: "TCTVARIETYLSSI02240PKS", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 0 units", type: "purple", days: "134 days", daysColor: "purple" },
        stock: { current: 771, incoming: 138003, preorder: 0, reserved: 20 },
        oos: { date: "24.02.2026", eta: "12 hours ago", tone: "red" },
        reach: { days: "9 days", label: "Out of stock", segs: [0, 0, 0, 0, 0] },
        oosImpact: { ok: false, potential: false, value: "156k €", units: "1642 units" },
        relCurrent: null, relIncoming: { value: "1.108.252 €", units: "59111 units releasable" }, oosImpactSort: 156000 },

    { id: 17, badges: [], name: "Black & Navy Active V-Neck 2-l", size: "S", sku: "TCT41030BLKNFY2PKS", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 5004 units", type: "purple", days: "117 days", daysColor: "purple" },
        stock: { current: 779, incoming: 5000, preorder: 0, reserved: 3 },
        oos: { date: "05.03.2026", eta: "in 9 days", tone: "red" },
        reach: { days: "9 days", label: "Out of stock", segs: [0, 0, 0, 0, 0] },
        oosImpact: { ok: false, potential: false, value: "104k €", units: "1487 units" },
        relCurrent: null, relIncoming: null, oosImpactSort: 104000 },

    { id: 18, badges: ["new"], name: "All Black Active V-Neck 2-Pack", size: "", sku: "TCT41035ALL8LACK2PKS", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 358 units", type: "purple", days: "31 days", daysColor: "red" },
        stock: { current: 0, incoming: 8000, preorder: 0, reserved: 1 },
        oos: { date: "23.02.2026", eta: "a day ago", tone: "red" },
        reach: { days: "0 days", label: "Out of stock", segs: [0, 0, 0, 0, 0] },
        oosImpact: { ok: false, potential: false, value: "72,9k €", units: "1642 units" },
        relCurrent: null, relIncoming: null, oosImpactSort: 72900 },

    { id: 19, badges: [], name: "All Navy Waffle Long Sleeve Crew", size: "", sku: "TCT4205ALLNWYS", warehouses: 2, wh: "2 warehouses",
        reorder: { label: "Reorder 5802 units", type: "purple", days: "14 days", daysColor: "red" },
        stock: { current: 3306, incoming: 15429, preorder: 0, reserved: 12 },
        oos: { date: "12.03.2026", eta: "in 16 days", tone: "red" },
        reach: { days: "16 days", label: "Reorder", segs: [1, 0, 0, 0, 0] },
        oosImpact: { ok: false, potential: false, value: "4,7k €", units: "86 units" },
        relCurrent: null, relIncoming: null, oosImpactSort: 4700 },

    { id: 20, badges: ["new"], name: "Black Boxer Briefs 6-Pack", size: "M", sku: "TCT3000BLACKSPACKSM", warehouses: 1, wh: "Example Warehouse...",
        reorder: { label: "Reorder 0 units", type: "purple", days: "134 days", daysColor: "purple" },
        stock: { current: 0, incoming: 20000, preorder: 30, reserved: 0 },
        oos: { date: "23.02.2026", eta: "a day ago", tone: "red" },
        reach: { days: "0 days", label: "Out of stock", segs: [0, 0, 0, 0, 0] },
        oosImpact: { ok: false, potential: false, value: "1,7k €", units: "24 units" },
        relCurrent: null, relIncoming: { value: "174.400 €", units: "19034 units releasable" }, oosImpactSort: 1700 },
];

export const MOCK_FORECAST_TABS: ForecastTab[] = [
    { id: "all", label: "All", count: 114 },
    { id: "compact", label: "Compact", count: 114 },
    { id: "reorder", label: "Reorder", count: 51 },
    { id: "overstock", label: "Overstock", count: 26 },
    { id: "demand", label: "Demand Shaping Only", count: 2 },
    { id: "fba", label: "FBA Transfer", count: 55 },
    { id: "stella", label: "Stella", count: 114 },
    { id: "anielka", label: "Anielka", count: 114 },
    { id: "top", label: "Top seller", count: 3 },
    { id: "low", label: "Low Sellers", count: 70 },
    { id: "ovall", label: "Overstock (all)", count: 45 },
];
