import type { AlertRow, AlertCountsResult } from "@/actions/alerts";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000);

export const MOCK_CMO_ALERTS: AlertRow[] = [
  {
    id: "mock-cmo-1",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CMO",
    type: "PRICE_DROP",
    severity: "HOT",
    status: "OPEN",
    title: "Price dropped 12%",
    description: "Canon dropped their EOS R5 kit price for the 2nd time this week.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: "foto-erhardt",
    estimatedImpact: 9460,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Canon EOS R5 Kit 24-105mm",
      sku: "CEOSR5-KIT-24105",
      myPrice: "2499.00",
      competitorPrice: "2199.00",
      priceDeltaPct: -12,
      competitorName: "Foto Erhardt",
      contextSnippet: "Canon dropped price 2nd time this week — now €300 below our listing",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(0),
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: "mock-cmo-2",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CMO",
    type: "COMPETITOR_NEW_PRODUCT",
    severity: "WARM",
    status: "OPEN",
    title: "New variant launched",
    description: "Fotokoch added a new Sony A7 IV bundle with 2-year warranty.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: "fotokoch",
    estimatedImpact: 14200,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Sony A7 IV Body",
      sku: "SONYA7IV-BODY",
      myPrice: "2799.00",
      competitorPrice: "2749.00",
      competitorName: "Fotokoch",
      contextSnippet: "Fotokoch launched Sony A7 IV + 2yr warranty bundle — undercuts by €50",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(1),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "mock-cmo-3",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CMO",
    type: "PROMO_START",
    severity: "WARM",
    status: "OPEN",
    title: "Promo started",
    description: "Amazon DE launched a 3-day flash sale on camera accessories.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: "amazon-de",
    estimatedImpact: 5800,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Manfrotto 190X Tripod",
      sku: "MFOTT-190X",
      myPrice: "199.00",
      competitorPrice: "169.00",
      priceDeltaPct: -15,
      competitorName: "Amazon DE",
      contextSnippet: "Amazon 3-day flash sale — 15% off tripods and accessories",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(2),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "mock-cmo-4",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CMO",
    type: "AD_CREATIVE_CHANGE",
    severity: "COLD",
    status: "OPEN",
    title: "Ad creative updated",
    description: "MediaMarkt refreshed their Instagram creative for Sony lenses.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: "mediamarkt",
    estimatedImpact: 3200,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Sony FE 85mm f/1.4 GM",
      sku: "SONY-FE85GM",
      competitorName: "MediaMarkt",
      contextSnippet: "MediaMarkt swapped to lifestyle photography creative — 3rd update this month",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(3),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "mock-cmo-5",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CMO",
    type: "PRICE_INCREASE",
    severity: "COLD",
    status: "OPEN",
    title: "Price increased 8%",
    description: "Foto Erhardt increased Nikon Z8 body price following supply constraints.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: "foto-erhardt",
    estimatedImpact: 7100,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Nikon Z8 Body",
      sku: "NIKZ8-BODY",
      myPrice: "3699.00",
      competitorPrice: "3999.00",
      priceDeltaPct: 8,
      competitorName: "Foto Erhardt",
      contextSnippet: "Foto Erhardt raised Nikon Z8 by €300 — opportunity to capture demand",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(4),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: "mock-cmo-6",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CMO",
    type: "COMPETITOR_STOCKOUT",
    severity: "HOT",
    status: "OPEN",
    title: "Fotokoch out of stock",
    description: "Fotokoch is out of stock on the Fujifilm X-T5 — major demand opportunity.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: "fotokoch",
    estimatedImpact: 18900,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Fujifilm X-T5 Body",
      sku: "FUJIXT5-BODY",
      myPrice: "1799.00",
      competitorName: "Fotokoch",
      contextSnippet: "Fotokoch shows OOS on Fujifilm X-T5 — we're the only listed stock",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(0),
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: "mock-cmo-7",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CMO",
    type: "NEWSLETTER_RECEIVED",
    severity: "COLD",
    status: "OPEN",
    title: "Newsletter from Amazon DE",
    description: "Amazon DE sent a photography deals newsletter to ~2M subscribers.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: "amazon-de",
    estimatedImpact: 2100,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      competitorName: "Amazon DE",
      contextSnippet: "Amazon DE photography newsletter — 14 product features, 3 overlap with our catalog",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: "mock-cmo-8",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CMO",
    type: "PROMO_END",
    severity: "COLD",
    status: "OPEN",
    title: "Promo ended",
    description: "MediaMarkt ended their summer sale — prices back to normal.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: "mediamarkt",
    estimatedImpact: 1400,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      competitorName: "MediaMarkt",
      contextSnippet: "MediaMarkt summer sale ended — competitor pricing normalised",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(6),
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
];

export const MOCK_CFO_ALERTS: AlertRow[] = [
  {
    id: "mock-cfo-1",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CFO",
    type: "STOCKOUT_IMMINENT",
    severity: "HOT",
    status: "OPEN",
    title: "Stockout in 3d",
    description: "Canon EOS R5 stock will hit zero within 3 days at current sell-through.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: null,
    estimatedImpact: 22400,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Canon EOS R5 Body",
      sku: "CEOSR5-BODY",
      stockUnits: 12,
      reorderPoint: 50,
      daysUntilStockout: 3,
      supplierLeadDays: 14,
      contextSnippet: "Supplier lead time 14d — reorder by tomorrow to avoid stockout",
      reorderBy: new Date(now.getTime() + 1 * 86400000).toISOString(),
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(0),
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: "mock-cfo-2",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CFO",
    type: "REORDER_POINT_HIT",
    severity: "WARM",
    status: "OPEN",
    title: "Reorder point reached",
    description: "Sony A7 IV stock has crossed the reorder threshold.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: null,
    estimatedImpact: 14600,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Sony A7 IV Body",
      sku: "SONYA7IV-BODY",
      stockUnits: 45,
      reorderPoint: 50,
      supplierLeadDays: 21,
      contextSnippet: "Supplier lead time 21d — reorder by Apr 25 to maintain buffer",
      reorderBy: new Date(now.getTime() + 5 * 86400000).toISOString(),
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(1),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "mock-cfo-3",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CFO",
    type: "LOW_INVENTORY",
    severity: "WARM",
    status: "OPEN",
    title: "2,700 units low",
    description: "Manfrotto tripod stock significantly below forecast demand.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: null,
    estimatedImpact: 8300,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Manfrotto 190X Pro Tripod",
      sku: "MFOTT-190X-PRO",
      stockUnits: 2700,
      reorderPoint: 5000,
      supplierLeadDays: 30,
      contextSnippet: "Forecast shows 4.2k units demand next 30d — current stock covers 19d only",
      reorderBy: new Date(now.getTime() + 10 * 86400000).toISOString(),
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(2),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "mock-cfo-4",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CFO",
    type: "OVERSTOCK",
    severity: "COLD",
    status: "OPEN",
    title: "45,200 units — overstock",
    description: "SD card inventory exceeds 90-day supply based on current sell-through.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: null,
    estimatedImpact: 3100,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "SanDisk Extreme Pro 128GB SD",
      sku: "SDXPRO-128-10PK",
      stockUnits: 45200,
      reorderPoint: 10000,
      contextSnippet: "45,200 units on hand — 6.3 months of supply at current velocity",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(3),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "mock-cfo-5",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CFO",
    type: "STOCKOUT_ACTIVE",
    severity: "HOT",
    status: "OPEN",
    title: "Stockout active",
    description: "Nikon Z8 is currently out of stock — losing sales now.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: null,
    estimatedImpact: 31200,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Nikon Z8 Body",
      sku: "NIKZ8-BODY",
      stockUnits: 0,
      reorderPoint: 20,
      daysUntilStockout: 0,
      supplierLeadDays: 28,
      contextSnippet: "Out of stock since 2 days — ETA from supplier Apr 30",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(2),
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "mock-cfo-6",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CFO",
    type: "LEAD_TIME_BREACH",
    severity: "WARM",
    status: "OPEN",
    title: "Lead time exceeded",
    description: "Fujifilm supplier exceeded agreed 14-day lead time by 16 days.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: null,
    estimatedImpact: 6700,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Fujifilm X-T5 Body",
      sku: "FUJIXT5-BODY",
      stockUnits: 8,
      supplierLeadDays: 30,
      contextSnippet: "Order placed 30d ago — agreed lead time was 14d, stock critical",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(4),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: "mock-cfo-7",
    companyId: "cmnw4qqo10000ltccgauemneu",
    audience: "CFO",
    type: "SUPPLIER_DELAY",
    severity: "WARM",
    status: "OPEN",
    title: "Supplier delay reported",
    description: "Sigma lens supplier reported 2-week delay due to component shortage.",
    subjectProductId: null,
    subjectVariantId: null,
    subjectCompetitorId: null,
    estimatedImpact: 4200,
    impactCurrency: "EUR",
    impactWindowDays: 180,
    metadata: {
      productTitle: "Sigma 24-70mm f/2.8 DG DN Art",
      sku: "SIGMA-2470-ART-E",
      stockUnits: 22,
      supplierLeadDays: 42,
      contextSnippet: "Sigma confirmed 2-week push — now ETA May 12 instead of Apr 28",
    },
    assignedToUserId: null,
    snoozeUntil: null,
    resolvedAt: null,
    resolvedByUserId: null,
    triggeredAt: daysAgo(1),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

export const MOCK_CMO_COUNTS: AlertCountsResult = {
  total: MOCK_CMO_ALERTS.length,
  HOT: MOCK_CMO_ALERTS.filter((a) => a.severity === "HOT").length,
  WARM: MOCK_CMO_ALERTS.filter((a) => a.severity === "WARM").length,
  COLD: MOCK_CMO_ALERTS.filter((a) => a.severity === "COLD").length,
  SNOOZED: 0,
  RESOLVED: 0,
  assigned: 0,
};

export const MOCK_CFO_COUNTS: AlertCountsResult = {
  total: MOCK_CFO_ALERTS.length,
  HOT: MOCK_CFO_ALERTS.filter((a) => a.severity === "HOT").length,
  WARM: MOCK_CFO_ALERTS.filter((a) => a.severity === "WARM").length,
  COLD: MOCK_CFO_ALERTS.filter((a) => a.severity === "COLD").length,
  SNOOZED: 0,
  RESOLVED: 0,
  assigned: 0,
};
