// Icon mapping from Lucide React to Untitled UI
// This ensures we can migrate icons incrementally without breaking functionality

import {
  SearchLg,
  FilterLines,
  XClose,
  ChevronDown,
  ArrowsUp,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  DotsVertical,
  Eye,
  Edit01,
  Copy01,
  Trash01,
  Star01,
  TrendUp01,
  CurrencyDollar,
  Tag01,
  Calendar,
  Settings01,
  Download01,
  Upload01,
  RefreshCw01,
  Grid01,
  List,
  Columns01,
  Zap,
  Target01,
  BarChart01,
  PieChart01,
  Activity,
  AlertCircle,
  CheckCircle,
  Clock,
  Minus,
  Plus,
} from "@untitledui/icons";

// Mapping object for easy migration
export const iconMapping = {
  Search: SearchLg,
  Filter: FilterLines,
  X: XClose,
  ChevronDown: ChevronDown,
  ArrowUpDown: ArrowsUp,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  ArrowLeft: ArrowLeft,
  ArrowRight: ArrowRight,
  MoreHorizontal: DotsVertical,
  Eye: Eye,
  Edit: Edit01,
  Copy: Copy01,
  Trash2: Trash01,
  Star: Star01,
  TrendingUp: TrendUp01,
  DollarSign: CurrencyDollar,
  Tag: Tag01,
  Calendar: Calendar,
  Settings: Settings01,
  Download: Download01,
  Upload: Upload01,
  RefreshCw: RefreshCw01,
  Grid3X3: Grid01,
  Grid01: Grid01,
  List: List,
  Columns: Columns01,
  SortAsc: ArrowUp,
  SortDesc: ArrowDown,
  FilterX: FilterLines,
  Zap: Zap,
  Target: Target01,
  BarChart3: BarChart01,
  PieChart: PieChart01,
  Activity: Activity,
  AlertCircle: AlertCircle,
  CheckCircle: CheckCircle,
  Clock: Clock,
  Minus: Minus,
  Plus: Plus,
} as const;

// Type for better TypeScript support
export type IconName = keyof typeof iconMapping;
